version: '2'

services:
  mon1:
    build: .
    image: hiropppe/mongo:3.0
    ports:
      - "27017:27017"
    user: root
    mem_limit: 1024m
  
  mon2:
    build: .
    image: hiropppe/mongo:3.0
    ports:
      - "27117:27017"
    user: root
    mem_limit: 1024m

  mon3:
    build: .
    image: hiropppe/mongo:3.0
    user: root

  ycsb:
    build: ./ycsb
    image: hiropppe/mongo-ycsb:0.3.1
    user: root
    volumes: 
        - /tmp/results:/tmp/results

